// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh0h_Aqt_Q3tUbg7Q5N3Lijdz-yj96aTI',
    appId: '1:549399449790:web:a25a7e9d4ec0a3ce95ceef',
    messagingSenderId: '549399449790',
    projectId: 'notifybear-5195a',
    authDomain: 'notifybear-5195a.firebaseapp.com',
    storageBucket: 'notifybear-5195a.appspot.com',
    measurementId: 'G-RECFESJV7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjBy7STYfD1smlO8m1IJUwvq5r-3nG8wM',
    appId: '1:549399449790:android:817f00f2efad476195ceef',
    messagingSenderId: '549399449790',
    projectId: 'notifybear-5195a',
    storageBucket: 'notifybear-5195a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6OBQRZPqZQPlZXAWNASzfW4_y9coeJk',
    appId: '1:549399449790:ios:b470ec360c66be2e95ceef',
    messagingSenderId: '549399449790',
    projectId: 'notifybear-5195a',
    storageBucket: 'notifybear-5195a.appspot.com',
    iosBundleId: 'com.example.notifybear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf6OBQRZPqZQPlZXAWNASzfW4_y9coeJk',
    appId: '1:549399449790:ios:b470ec360c66be2e95ceef',
    messagingSenderId: '549399449790',
    projectId: 'notifybear-5195a',
    storageBucket: 'notifybear-5195a.appspot.com',
    iosBundleId: 'com.example.notifybear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh0h_Aqt_Q3tUbg7Q5N3Lijdz-yj96aTI',
    appId: '1:549399449790:web:a3637187887624a195ceef',
    messagingSenderId: '549399449790',
    projectId: 'notifybear-5195a',
    authDomain: 'notifybear-5195a.firebaseapp.com',
    storageBucket: 'notifybear-5195a.appspot.com',
    measurementId: 'G-F0RVZ3QS6C',
  );
}
